InternshipManagement.Presentation/Models/user.cs
namespace InternshipManagement.Presentation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            categories = new HashSet<category>();
            departments = new HashSet<department>();
            enterprises = new HashSet<enterprise>();
            final_project_assignment = new HashSet<final_project_assignment>();
            grades = new HashSet<grade>();
            notifications = new HashSet<notification>();
            universities = new HashSet<university>();
            sheets = new HashSet<sheet>();
            validation_group = new HashSet<validation_group>();
            validation_group1 = new HashSet<validation_group>();
            validation_group2 = new HashSet<validation_group>();
            validation_group3 = new HashSet<validation_group>();
            validation_group4 = new HashSet<validation_group>();
            classes = new HashSet<_class>();
            categories1 = new HashSet<category>();
            occupations = new HashSet<occupation>();
            roles = new HashSet<role>();
        }

        public long id { get; set; }

        public bool activated { get; set; }

        [StringLength(255)]
        public string descriminator { get; set; }

        [StringLength(255)]
        public string email { get; set; }

        [StringLength(255)]
        public string first_name { get; set; }

        [StringLength(255)]
        public string lang_key { get; set; }

        [StringLength(255)]
        public string last_name { get; set; }

        [StringLength(255)]
        public string login { get; set; }

        [StringLength(255)]
        public string password { get; set; }

        [StringLength(255)]
        public string reset_key { get; set; }

        [StringLength(255)]
        public string token { get; set; }

        public long? univerity_id { get; set; }
        public long? sheet_id { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<category> categories { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<department> departments { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<enterprise> enterprises { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<final_project_assignment> final_project_assignment { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grade> grades { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }

        public virtual university university { get; set; }
        public virtual sheet sheet { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<university> universities { get; set; }
        public virtual ICollection<sheet> sheets { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<validation_group> validation_group { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<validation_group> validation_group1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<validation_group> validation_group2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<validation_group> validation_group3 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<validation_group> validation_group4 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<_class> classes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<category> categories1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<occupation> occupations { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<role> roles { get; set; }
    }
}

InternshipManagement.Presentation/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Net.Mail;

using System.Web.Mvc;
using InternshipManagement.Presentation.Models;

namespace InternshipManagement.Presentation.Controllers
{
    public class usersController : Controller
    {
        private Internship db = new Internship();

        // GET: users
        public async Task<ActionResult> Index()
        {
            var users = db.users.Include(u => u.university).Include(u => u.sheet).Where(u => u.sheet_id != null);

            return View(await users.ToListAsync());
        }
        public async Task<ActionResult> IndexWithoutFiche()
        {
            var users = db.users.Include(u => u.university).Include(u => u.sheet).Where(u=>u.sheet_id == null);
            
            return View(await users.ToListAsync());
        }


        public  void sendMail(string email)
        {
            var body = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
            var message = new MailMessage();
            message.To.Add(new MailAddress(email));  // replace with valid value 
            message.From = new MailAddress("directeur.stages@gmail.com");  // replace with valid value
            message.Subject = "Reminder";
            message.Body = string.Format(body, "Reminder", "no-reply@internship.com", "You must fill your sheet");
            message.IsBodyHtml = true;

            using (var smtp = new SmtpClient())
            {
                var credential = new NetworkCredential
                {
                    UserName = "directeur.stages@gmail.com",  // replace with valid value
                    Password = "1234wK@@"  // replace with valid value
                };
                smtp.Credentials = credential;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.EnableSsl = true;
                smtp.Send(message);
            }


        }


        public  ActionResult Reminder()
        {
            var users = db.users.Include(u => u.university).Include(u => u.sheet).Where(u => u.sheet_id != null );
            foreach (user element in users)
            {
                sendMail(element.email);
            }
              return RedirectToAction("IndexWithoutFiche");

        }


        // GET: users/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = await db.users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: users/Create
        public ActionResult Create()
        {
            ViewBag.univerity_id = new SelectList(db.universities, "id", "email");
            return View();
        }

        // POST: users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,activated,descriminator,email,first_name,lang_key,last_name,login,password,reset_key,token,univerity_id")] user user)
        {
            if (ModelState.IsValid)
            {
                db.users.Add(user);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.univerity_id = new SelectList(db.universities, "id", "email", user.univerity_id);
            return View(user);
        }

        // GET: users/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = await db.users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.univerity_id = new SelectList(db.universities, "id", "email", user.univerity_id);
            return View(user);
        }

        // POST: users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,activated,descriminator,email,first_name,lang_key,last_name,login,password,reset_key,token,univerity_id")] user user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.univerity_id = new SelectList(db.universities, "id", "email", user.univerity_id);
            return View(user);
        }

        // GET: users/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            user user = await db.users.FindAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            user user = await db.users.FindAsync(id);
            db.users.Remove(user);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InternshipManagement.Presentation/Views/users/Create.cshtml
@model InternshipManagement.Presentation.Models.user

@{
    ViewBag.Title = "Create";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>user</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.activated, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.activated)
                        @Html.ValidationMessageFor(model => model.activated, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.descriminator, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descriminator, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descriminator, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.lang_key, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.lang_key, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.lang_key, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.login, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.login, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.login, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.reset_key, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.reset_key, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.reset_key, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.token, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.token, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.token, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.univerity_id, "univerity_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("univerity_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.univerity_id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

InternshipManagement.Presentation/Views/users/Delete.cshtml
@model InternshipManagement.Presentation.Models.user

@{
    ViewBag.Title = "Delete";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>user</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.university.email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.university.email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.activated)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.activated)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.descriminator)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.descriminator)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.first_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.first_name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.lang_key)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.lang_key)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.last_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.last_name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.login)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.login)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.password)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.password)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.reset_key)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.reset_key)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.token)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.token)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

InternshipManagement.Presentation/Views/users/Details.cshtml
@model InternshipManagement.Presentation.Models.user

@{
    ViewBag.Title = "Details";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>user</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.university.email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.university.email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.activated)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.activated)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.descriminator)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.descriminator)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.first_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.first_name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.lang_key)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.lang_key)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.last_name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.last_name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.login)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.login)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.password)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.password)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.reset_key)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.reset_key)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.token)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.token)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

InternshipManagement.Presentation/Views/users/Edit.cshtml
@model InternshipManagement.Presentation.Models.user

@{
    ViewBag.Title = "Edit";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>user</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.activated, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.activated)
                        @Html.ValidationMessageFor(model => model.activated, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.descriminator, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descriminator, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descriminator, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.lang_key, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.lang_key, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.lang_key, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.login, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.login, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.login, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.reset_key, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.reset_key, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.reset_key, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.token, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.token, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.token, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.univerity_id, "univerity_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("univerity_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.univerity_id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

InternshipManagement.Presentation/Views/users/Index.cshtml
@model IEnumerable<InternshipManagement.Presentation.Models.user>

@{
    ViewBag.Title = "Index";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    
    <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>
                    University
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.activated)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.first_name)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.last_name)
                </th>




                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.university.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.activated)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.first_name)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.last_name)
            </td>




            <td>
                
                @Html.ActionLink("voir fiche", "Details", "sheets", new { id = item.sheet_id }, new { @class="btn btn-primary"}) 

            </td>
            <td>

                @Html.ActionLink("Edit Student", "Edit", "users", new { id = item.id }, new { @class = "btn btn-primary" })
            </td>
        </tr>
}
        </tbody>
    </table>
</body>
</html>